### PR TITLE
Simplify and improve the ping mechanism

### PR DESCRIPTION
**Pull request by calmh**
This should resolve the spurious ping timeouts we've had on low powered
boxes. Those errors are the result of us requiring a timely Pong
response to our Pings. However this is unnecessarily strict - as long as
we've received *anything* recently, we know the other peer is alive. So
the new mechanism removes the Pong message entirely and separates the
ping check into two routines:

 - One that makes sure to send ping periodically, if nothing else has
   been sent. This guarantees a message sent every 45-90 seconds.

 - One that checks how long it was since we last received a message. If
   it's longer than 300 seconds, we trigger an ErrTimeout.

So we're guaranteed to detect a connection failure in 300 + 300/2
seconds (due to how often the check runs) and we may detect it much
sooner if we get an actual error on the ping write (a connection reset
or so).

This is more sluggish than before but I think that's an OK price to pay
for making it actually work out of the box.

This removes the configurability of it, as the timeout on one side is
dependent on the send interval on the other side. Do we still need it
configurable?

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I feel that the ping message doesn't get sent because the ping routine just doesn't get any time to run, and scan routine being pegged on the thread, so actually nothing is being sent out.

**Comment by calmh** [comment]
I don't think that's the case. The Go scheduler should handle that just fine... What I saw was that we had for example a hundred IndexUpdate messages queued for send, and our Ping request after those. The Pong would come eventually, but not before the other side had processed those one hundred IndexUpdates and actually got to it.

**Comment by AudriusButkevicius** [comment]
Ok lets try this, we can always add it back.

**Comment by AudriusButkevicius** [comment]
This needs an acompanying part in the binary.

**Comment by calmh** [comment]
Yep, coming.

**Pull request merged**
