### PR TITLE
Changes for temp indexes

### PR DESCRIPTION
**Pull request by AudriusButkevicius**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
why?

**Comment by calmh** [comment]
Erm. I was as surprised as you. I think I deleted the branch by mistake while cleanup my local repo and pushed the delete. Sorry!

**Comment by AudriusButkevicius** [comment]
No reason why this couldn't be merged?

**Comment by AudriusButkevicius** [comment]
Here, added comments.

**Comment by AudriusButkevicius** [comment]
Bump.

**Comment by calmh** [comment]
Woops, I suck. Reviewing tonight!

**Comment by AudriusButkevicius** [comment]
This needs one of the patches from syncthing's temp index series to be cherry-picked to be exactly noop functionality wise.

**Comment by calmh** [comment]
LGTM, nothing really controversial in here. Maybe rebase to be a bit closer to the top of the commit tree, and combine with a change to syncthing to add the new parameters etc (I guess that's what you mean above?) and it's all good by me.

**Pull request merged**
