### PR TITLE
Base for better conflict resolution

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
Not sure why this has to be here, but I guess it can be.

**Comment by calmh** [comment]
It doesn't really, but I thought having it here would make it a de facto part of the protocol, and it's better if everyone agrees on who wins a conflict.

**Comment by AudriusButkevicius** [comment]
I feel it could be configurable by the user, just like the pull order. Also, are we sure that moving a non-existing file for conflict is not going to blow up?

**Comment by calmh** [comment]
Yiure right about the configurability. Unfortunate the decision is made in an annoying place (the db driver) - perhaps it should pass that stuff to the model instead for resolution. I don't immediately see in front of me how that would work though, code wise, but it's of course possible. :)

**Comment by AudriusButkevicius** [comment]
I don't really care where it happens, but adding a new method of resolution now requires a godep dance and multiple PRs.

**Comment by calmh** [comment]
Yeah. I think when that happens, the logic needs to be moved.

**Pull request merged**
